import type { BrandConfig } from "@/types/brand";

const BANNED = [
  "혁신적",
  "혁신",
  "융합",
  "솔루션",
  "시너지",
  "패러다임",
  "선도",
  "최고의",
  "차세대",
  "임팩트",
  "스케일",
  "피벗",
];
const KEYWORDS = ["풀어내다", "연결", "흩어진", "형태", "실제로"];

export const STUDIO_SOLUTA_SEED: BrandConfig = {
  name: "studio.soluta",
  colors: {
    primary: "#1A1A18",
    secondary: "#5C5A55",
    accent: "#697C70",
    background: "#F5F4F0",
    surface: "#EEEAE0",
    line: "#E5E1D8",
    dark: "#181816",
    accentDark: "#A6A999",
    eucalyptus: "#98AA9D",
    dusty: "#8496A2",
    soot: "#2D3536",
  },
  fonts: {
    heading: "Cormorant Garamond",
    body: "Pretendard Variable",
    mono: "JetBrains Mono",
  },
  customFonts: [],
  logoPath: null,
  styleKeywords: ["warm paper", "minimal", "editorial", "calm"],
  voice: {
    ending: "합니다체",
    banned: BANNED,
    keywords: KEYWORDS,
    language: {
      preferredPhrases: [
        "흩어진 일을 형태로 정리",
        "실제로 쓰이는 구조",
        "작게 시작하는 운영",
        "필요한 만큼만 선명하게",
      ],
      avoidPhrases: [
        "AI가 대신 다 해줍니다",
        "누구나 쉽게 성공",
        "브레인 포그",
        "명료함을 되찾다",
      ],
      headlinePatterns: [
        "추상어보다 작업 장면에서 시작",
        "짧은 명사구 뒤에 조용한 설명",
        "과장 없이 문제와 구조를 나란히 둠",
      ],
      writingRules: [
        "차분하지만 차갑지 않게 쓴다",
        "자기평가와 과장 표현을 피한다",
        "도구보다 작업자의 판단을 먼저 둔다",
      ],
      sampleLines: [
        "흩어진 일을 다시 볼 수 있게",
        "작게 시작해 실제 흐름으로",
        "필요한 만큼만 선명하게 정리합니다",
      ],
    },
  },
  createdAt: "",
  updatedAt: "",
};

export const POGON_SEED: BrandConfig = {
  name: "포곤 FOGGONE",
  colors: {
    primary: "#2F3A34",
    secondary: "#727771",
    accent: "#8FA394",
    background: "#F7F5F0",
    surface: "#E8ECE4",
    line: "#D8D8CF",
    dark: "#202724",
    accentDark: "#B8C6BA",
    eucalyptus: "#9BAE9F",
    dusty: "#9DA8AF",
    soot: "#3B4240",
  },
  fonts: {
    heading: "Pretendard",
    body: "Pretendard",
    mono: "DM Mono",
  },
  customFonts: [],
  logoPath: null,
  styleKeywords: [
    "fog-clearing",
    "quiet recovery",
    "low contrast",
    "soft negative space",
    "routine editorial",
    "calm but not generic",
  ],
  voice: {
    ending: "합니다체",
    banned: [
      ...BANNED,
      "과장된 뷰티 광고",
      "병원식 효능 표현",
      "generic skincare tips",
      "효능 보장",
      "치료",
      "즉각 개선",
      "완치",
    ],
    keywords: [
      "예민함",
      "지침",
      "회복",
      "차분함",
      "흐림",
      "맑아짐",
      "정돈",
      "전환",
      "루틴",
      "호흡",
      "잔잔함",
      "집중",
      "명료함",
      "낮은 대비",
      "여백",
    ],
    language: {
      preferredPhrases: [
        "브레인 포그",
        "머릿속 안개",
        "집중과 명료함",
        "일상 컨디션 관리",
        "하루의 에너지",
        "자연 유래 캡사이신",
        "편안한 온기",
        "일상 루틴",
      ],
      avoidPhrases: [
        "기준이 필요합니다",
        "먼저 세 가지를 봅니다",
        "자극보다 정돈",
        "작은 루틴으로 전환",
        "흐린 날의 기준",
        "저장합니다",
        "흰 고양이",
        "실타래",
        "엉킨 마음",
      ],
      headlinePatterns: [
        "브레인 포그 상황에서 시작해 집중·명료함으로 넘어간다",
        "효능 단정 대신 일상 컨디션 관찰로 쓴다",
        "제품 성분은 자연 유래 캡사이신처럼 사실 표현으로 짧게 둔다",
        "CTA는 저장보다 오늘의 루틴 점검으로 유도한다",
      ],
      writingRules: [
        "정돈, 기준, 전환 같은 추상어만으로 헤드라인을 만들지 않는다",
        "브랜드 원문에 있는 브레인 포그, 집중, 명료함, 컨디션, 에너지 언어를 우선한다",
        "치료·개선·보장처럼 의학적 효능으로 읽히는 문장을 피한다",
        "studio.soluta 캐릭터나 문장 습관을 가져오지 않는다",
      ],
      sampleLines: [
        "브레인 포그가 찾아온 오후",
        "집중이 필요한 날의 컨디션 루틴",
        "머릿속 안개를 가볍게 넘기는 방법",
        "명료한 하루를 위한 작은 온기",
      ],
    },
  },
  kit: {
    description: "브레인 포그가 찾아온 일상에 집중과 명료함의 선택지를 제안하는 컨디션 관리 브랜드",
    metaphor: "머릿속 안개가 걷히며 하루의 집중감을 되찾는 장면",
    character: "크림색의 둥근 구름형 캐릭터. 머리 위에 초록 잎 또는 클로버가 있고, 두 손으로 머리와 볼을 감싼 표정과 파란 물결선으로 브레인 포그와 지친 머릿속을 표현한다.",
    emotionalRange: ["무거움", "멍함", "지침", "편안함", "명료함"],
    visualTone: ["밝은 하늘색", "포근한 크림색", "노란 포인트", "둥근 캐릭터", "파란 물결선"],
    forbiddenDirections: [
      "과장된 뷰티 광고",
      "병원식 효능 표현",
      "일반적인 피부 관리 팁처럼 보이는 구성",
      "자극적인 before-after",
      "제작 도구 브랜드 노출",
      "studio soluta 캐릭터 차용",
      "고양이 또는 실타래 캐릭터 사용",
      "포곤 캐릭터를 생략한 텍스트 카드만의 구성",
    ],
    repeatLimits: [
      "순하게, 차근차근 같은 안전한 표현을 반복하지 않는다",
      "같은 배경 카드가 세 장 이상 이어지지 않게 한다",
    ],
    assetHints: [
      "크림색 구름형 포곤 캐릭터",
      "머리 위 초록 잎 또는 클로버",
      "브레인 포그를 나타내는 파란 물결선",
      "포곤 집중 루틴세트 패키지",
      "브레인 액티브 롤온과 포인트 패치",
    ],
  },
  createdAt: "",
  updatedAt: "",
};

export function blankBrandTemplate(): BrandConfig {
  return {
    name: "",
    colors: {
      primary: "#1A1A18",
      secondary: "#5C5A55",
      accent: "#697C70",
      background: "#F5F4F0",
      surface: "#EEEAE0",
      line: "#E5E1D8",
    },
    fonts: {
      heading: "Cormorant Garamond",
      body: "Pretendard Variable",
      mono: "JetBrains Mono",
    },
    customFonts: [],
    logoPath: null,
    styleKeywords: [],
    voice: { ending: "합니다체", banned: BANNED, keywords: [] },
    createdAt: "",
    updatedAt: "",
  };
}
